name: build

on:
  push:
    tags:
      - '*'

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - uses: actions/checkout@master
      # create release
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      # build binaries
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13.5'
      - name: build
        run: go build -o pingme *.go
      - name: create artifacts
        run: |
          zip --junk-paths pingme.zip README.md pingme
      # upload binaries
      - uses: actions/upload-release-asset@v1.0.1
        id: upload-release-asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pingme.zip
          asset_name: pingme.zip
          asset_content_type: application/zip
